### ISSUE TITLE
Crash after inputting context and prompt

### ISSUE THREAD

**Issue by Parkman202** [cloveranon/Clover-Edition#124] opened 2020-02-11 22:04 UTC
I'm encountering a traceback error immediately after I input my context, prompt, and save file preferences (I chose no save file and told the autosave to nae my file "aaaa"). Immediately after I input them, I get this:

```
Traceback (most recent call last):
  File "play.py", line 758, in <module>
    gm.play_story()
  File "play.py", line 697, in play_story
    if not self.init_story():  # Failed init
  File "play.py", line 423, in init_story
    self.story = new_story(self.generator, self.context, self.prompt)
  File "play.py", line 211, in new_story
    story.act(prompt)
  File "C:\Users\me\OneDrive\Desktop\AIDungeonCE\storymanager.py", line 29, in act
    repetition_penalty=settings.getfloat('rep-pen'))
  File "C:\Users\me\OneDrive\Desktop\AIDungeonCE\gpt2generator.py", line 335, in generate
    stop_tokens=self.tokenizer.encode(["<|endoftext|>", ">"])
  File "C:\Users\me\OneDrive\Desktop\AIDungeonCE\gpt2generator.py", line 303, in generate_raw
    stop_tokens=stop_tokens,
  File "C:\Users\me\OneDrive\Desktop\AIDungeonCE\gpt2generator.py", line 245, in sample_sequence
    tokenizer=self.tokenizer
  File "C:\Users\me\OneDrive\Desktop\AIDungeonCE\gpt2generator.py", line 128, in sample_sequence
    logits, pasts = model(input_ids=input_ids_next, past=pasts)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\me\OneDrive\Desktop\AIDungeonCE\gpt2.py", line 171, in forward
    hidden_states, pasts = self.transformer(input_ids, **kwargs)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\me\OneDrive\Desktop\AIDungeonCE\gpt2.py", line 151, in forward
    hidden_states, present = trans_block(hidden_states, layer_past, mask)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\me\OneDrive\Desktop\AIDungeonCE\gpt2.py", line 109, in forward
    a, present = self.attn(self.ln_1(x), layer_past, mask)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\me\OneDrive\Desktop\AIDungeonCE\gpt2.py", line 59, in forward
    x = self.c_attn(x)
  File "C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\nn\modules\module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\me\OneDrive\Desktop\AIDungeonCE\gpt2.py", line 23, in forward
    self._weightT = self.weight.T
AttributeError: 'Parameter' object has no attribute 'T'
```

Is there something I'm doing wrong? I'm pretty sure there's something going wrong with my PyTorch install or something based on this readout, but I'm not sure.

Thanks!

**Comment by SammCheese** [comment] 2021-05-06 03:30
Unfortunately, I cannot reproduce this issue, it also seems to be quite old so I will close it for now.
If you still experience that error, please open a new issue or comment below!

**Closed by SammCheese** 2021-05-06 03:30 UTC
