### ISSUE TITLE
Error when continuing a story

### ISSUE THREAD

**Issue by OcelotMadness** [cloveranon/Clover-Edition#191] opened 2021-05-28 18:56 UTC
Whenever I try continuing my story I get this error:
Traceback (most recent call last):
  File "C:\AID2 Clover Edition\aidungeon\__init__.py", line 52, in <module>
    gm.play_story()
  File "C:\AID2 Clover Edition\aidungeon\play.py", line 738, in play_story
    if self.process_action(action, suggested_actions):  # End of story
  File "C:\AID2 Clover Edition\aidungeon\play.py", line 667, in process_action
    result = self.story.act(action)
  File "C:\AID2 Clover Edition\aidungeon\storymanager.py", line 21, in act
    assert (self.context.strip() + action.strip())
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AID2 Clover Edition\launch.py", line 1, in <module>
    import aidungeon
  File "C:\AID2 Clover Edition\aidungeon\__init__.py", line 67, in <module>
    exit(1)
NameError: name 'exit' is not defined

[process exited with code 1]

I've already tried reinstalling which didn't seem to fix it I also looked at line 52 of __init__.py in notepad+ and as I'm unfamiliar with python I don't know whats happening

**Comment by MikkoMMM** [comment] 2021-05-28 19:07
Duplicate of #121. Hopefully it'll get fixed at some point; that issue is over a year old.

**Closed** 2021-05-28 19:16 UTC
