### ISSUE TITLE
If the input stops with a first person pronoun, it isn't converted to second person

### ISSUE THREAD

**Issue by MikkoMMM** [cloveranon/Clover-Edition#43] opened 2019-12-31 22:00 UTC
At least I think that's the issue. See these examples:

> You and I like myself
For REAL: You and you like myself.

> You are a huge fan of me, myself and I
For REAL: You start to are a huge fan of you, yourself and I.

(That last one also shows how the D20 thing sometimes produces grammatically incorrect sentences but that would possibly be a near-endless swamp to truly fix)

**Comment by AIDungeonWiXAnon** [comment] 2020-01-04 05:47
Bug-tested and confirmed to be fixed as of 9e31270. Looks like it was just a problem of not checking for EOL first person pronouns without any punctuation, since the first->second conversion is done before the addition of the "." for formatting

**Closed by AIDungeonWiXAnon** 2020-01-04 05:47 UTC
