### ISSUE TITLE
Model generated empty text/Constant Looping

### ISSUE THREAD

**Issue by Gabriram** [cloveranon/Clover-Edition#10] opened 2019-12-25 04:53 UTC
```
quite some time now and have seen a lot of action.

"We're going up!"

Woops that action caused the model to start looping. Try a different action to prevent that.

> Lift off
>> You try to lift off.
Woops that action caused the model to start looping. Try a different action to prevent that.

> Get into your F-16
>> You get into your F-16.
Woops that action caused the model to start looping. Try a different action to prevent that.

> 3
>> You start to ...
12/25/2019 05:4806 - WARNING - Model generated empty text .
Woops that action caused the model to start looping. Try a different action to prevent that.
```
dunno why its doing this, its not just with this prompt its with all of them, also the suggested actions seem very random for some reason?

**Comment by Meanmelter** [comment] 2019-12-25 05:07
Do you have anything in .\data\stories?

**Comment by cloveranon** [comment] 2019-12-25 05:08
What's your repetition penalty set to? Try increasing it.

The temp on suggested action is 1. I'm thinking we should reduce it, we wanted it to be a little more random to give a diverse set of suggestions. I think the repetition filter should be turned off for it, or possibly even set below 1.

**Comment by Gabriram** [comment] 2019-12-25 05:59
theres no data\stories folder? just some py files there, i was downloading everything again to see if it was something i did. still does it with a clean download.

**Comment by AccidentallyOnPurpose** [comment] 2019-12-25 06:48
I think I fixed that with #12 , should be much reduced now

**Comment by AccidentallyOnPurpose** [comment] 2019-12-25 06:49
Apparently it's been doing this the whole time, it was just silent before, and it kept silently retrying we thought it was hanging. So I set it try to once... lots of errors. Now I've set it to try 4 times, lets see if that reduces it.

**Comment by Gabriram** [comment] 2019-12-25 07:01
Ok Then i will close the Issue, it seems to have been fixxed.

**Comment by Nalewa** [comment] 2019-12-25 09:37
@Meanmelter can you upload .\data\stories\ cause after longer session I start to get 
`WARNING - Model generated empty text 4 times. Try another action`
and changing actions does nothing. I want to check if adding \stories\ can change behaviour of AI. 
I don't see this folder on thadunge2 repo.

**Comment by Nalewa** [comment] 2019-12-25 09:42
Huh, looping after first action
![image](https://user-images.githubusercontent.com/42716753/71441731-f90cb980-2702-11ea-8517-250fed273016.png)
(I know fireball isn't a Witchers' thing, I thought Agni will be too much for an AI)

**Comment by Gabriram** [comment] 2019-12-25 09:56
guess fireball is too much too

**Comment by AccidentallyOnPurpose** [comment] 2019-12-25 11:34
RebootTech (https://www.twitch.tv/reboottech) had a cool solution to fix looping and empty text on long stories. When he got that error he used a similarity comparison to do a fuzzy deduplicate of the story history. So he cleaned out the repetitive parts. Thay could be a cool thing to do some time.

**Comment by Nalewa** [comment] 2019-12-25 13:50
I tested for several hours (and played with settings) and I can tell something is off. Statistically the AI gives this message after 4-5 actions taken. 
```
12/25/2019 14:43:24 - WARNING - Model generated empty text 4 times. Try another action
Woops that action caused the model to start looping. Try a different action to prevent that.
```
Also sometimes the responses of AI are cutted, there is no dot or there are missing letters at the end of the last word (e.g. "running" is cutted to "runni"). I think current model doesn't like my actions and have nothing/don't know what to say.
I will wait for Meanmelter and try playing with .\data\stories\

**Comment by AccidentallyOnPurpose** [comment] 2019-12-25 13:57
Hmm tricky. Are you using suggested actions or your own?

**Comment by Nalewa** [comment] 2019-12-25 14:00
Both but mostly my own because sometimes proposed actions were bullshit (I didn't tried new branch though).

**Comment by AccidentallyOnPurpose** [comment] 2019-12-25 14:02
When it cuts off the words, is at the end of a long paragraph of story, or a short one? (or suggested actions?)

I ask because if it's at the end of a paragraph it might be the end of the 60 tokens it generates. Otherwise it might be a formatting issue.

**Comment by Nalewa** [comment] 2019-12-25 14:07
It can happen in both situations, but mostly it's cutting in the short responses.

**Comment by Nalewa** [comment] 2019-12-25 14:11
How can I enable debug log like this anon?
http://boards.4channel.org/v/thread/490089764#p490152219

**Comment by AccidentallyOnPurpose** [comment] 2019-12-25 14:13
good idea, in config.ini change log-level to 10

btw the branch seems to be more stable `new_suggestions_with_context` but maybe I just play in a boring way?

One good change was to generate the suggestions from "\n> You" instead of "\n> " so now they stay in third person.

**Comment by Nalewa** [comment] 2019-12-25 14:19
Ok I will try new branch and play for a while. And change log

**Comment by Nalewa** [comment] 2019-12-25 14:55
I had a decent long run by using suggestions and my own actions but then AI started to go crazy. When picked suggested action (please ignore my Fate fanfiction) the log showed this:
```
> 312/25/2019 15:38:08 - DEBUG - roll d20=5

>> You try to ask him why he isn't dead yet, you are sure he knows something about this..
12/25/2019 15:38:08 - DEBUG - Using history indices range(0, 7)
12/25/2019 15:38:08 - INFO - Generated action mem_ind=None, sample=False, include_prompt=True
12/25/2019 15:38:08 - DEBUG - BEFORE PROMPT_REPLACE: `"You are Guda of Chaldea, also known as Ritsuka Fujimaru. You got your ass kicked in Atlantis by Kirshtaria Wodime who sits now in Olympus. You lost you friends in the war with Artemis, Poseidon, Echidna, Odysseus and jobbers. You have only annoying Mashu by your side and loli da Vinci. In you hearth you know, if you don't kill Kirshtaria and you don't stop his Lostbelt form expanding everything will fall.\n"`
12/25/2019 15:38:08 - DEBUG - BEFORE PROMPT_REPLACE: `'\n> You try to ask da Vinci about the hole.\n She says she is not sure what it means but that there must be something important inside. So far you haven\'t found anything useful in this place so you decide to go find out.\nYou head back to the Nautilus where you met Mashu\n> You miserably fail to ask Mashu how she feel.\n You just want her to tell you how she feels because you can\'t do it yourself.\nThen you get an idea from Da Vinci\'s body and start running around like a madman. You run all over the ship and eventually you manage to reach the bridge\n> You try to head up into a hidden room on the ship.\n\nYou open the door and see a room full of machinery. There is no way you could fit through it, even if you had wings. However, you notice something very strange: there is a large hole in one of the walls\n> You start to go all the way into the hole..\n\nYou make it all the way into the wall and then suddenly you feel dizzy. It seems that you fell down into a pit. You look behind you and see nothing but darkness\n> You try to yell for help.\n\nYou scream and shout, but nobody hears you. Then you realize that you\'re trapped. The only thing you can think of to escape this situation is to use your magic powers to create a portal to leave this place\n> You expertly scream "Daybit please help me".\n\nSuddenly the voice of Daybits comes through the hole. He asks you why you came here and tells you that he has been trying to contact you since yesterday. He says he knows you were in the same class together and that he was going to give you some advice\n> You try to cry and say you are happy that he is here with you.\n\nHe says that he didn\'t expect you to come back alive and that he hopes you will find happiness in your new life'`
12/25/2019 15:38:08 - DEBUG - BEFORE PROMPT_REPLACE: `"\n> You try to ask him why he isn't dead yet, you are sure he knows something about this..\n"`
12/25/2019 15:38:08 - DEBUG - Prompt is: `["You are Guda of Chaldea, also known as Ritsuka Fujimaru. You got your ass kicked in Atlantis by Kirshtaria Wodime who sits now in Olympus. You lost you friends in the war with Artemis, Poseidon, Echidna, Odysseus and jobbers. You have only annoying Mashu by your side and loli da Vinci. In you hearth you know, if you don't kill Kirshtaria and you don't stop his Lostbelt form expanding everything will fall.\n", '\n> You try to ask da Vinci about the hole.\n She says she is not sure what it means but that there must be something important inside. So far you haven\'t found anything useful in this place so you decide to go find out.\nYou head back to the Nautilus where you met Mashu\n> You miserably fail to ask Mashu how she feel.\n You just want her to tell you how she feels because you can\'t do it yourself.\nThen you get an idea from Da Vinci\'s body and start running around like a madman. You run all over the ship and eventually you manage to reach the bridge\n> You try to head up into a hidden room on the ship.\n\nYou open the door and see a room full of machinery. There is no way you could fit through it, even if you had wings. However, you notice something very strange: there is a large hole in one of the walls\n> You start to go all the way into the hole..\n\nYou make it all the way into the wall and then suddenly you feel dizzy. It seems that you fell down into a pit. You look behind you and see nothing but darkness\n> You try to yell for help.\n\nYou scream and shout, but nobody hears you. Then you realize that you\'re trapped. The only thing you can think of to escape this situation is to use your magic powers to create a portal to leave this place\n> You expertly scream "Daybit please help me".\n\nSuddenly the voice of Daybits comes through the hole. He asks you why you came here and tells you that he has been trying to contact you since yesterday. He says he knows you were in the same class together and that he was going to give you some advice\n> You try to cry and say you are happy that he is here with you.\n\nHe says that he didn\'t expect you to come back alive and that he hopes you will find happiness in your new life', "\n> You try to ask him why he isn't dead yet, you are sure he knows something about this..\n"]`
12/25/2019 15:38:13 - DEBUG - Stopping generation as we found stop tokens. One of [29, 50256], in 'tensor([[29]], device='cuda:0')'. token generated 37
12/25/2019 15:38:13 - DEBUG - Generated result is: `"\n> You try to beg him to let you go.\nHe doesn't answer you, but instead he opens the door and leaves. You sigh deeply and close the portal.\n"`
12/25/2019 15:38:13 - DEBUG - Model generated empty text trying again 0
12/25/2019 15:38:13 - DEBUG - BEFORE PROMPT_REPLACE: `' 0'`
```
And it goes like this several minutes
```
You try to ask him why he isn't dead yet, you are sure he knows something about this..\n"]`
12/25/2019 15:40:01 - DEBUG - Stopping generation as we found stop tokens. One of [29, 50256], in 'tensor([[29]], device='cuda:0')'. token generated 45
12/25/2019 15:40:01 - DEBUG - Generated result is: `"\n> You try to beg him to save you.\nHe doesn't understand your language and tells you that he doesn't care about your begging, but he would rather die than live without hope.<|endoftext|"`
12/25/2019 15:40:01 - DEBUG - Model generated empty text trying again 17
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 17'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 16'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 15'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 14'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 13'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 12'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 11'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 10'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 9'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 8'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 7'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 6'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 5'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 4'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 3'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 2'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 1'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `' 0'`
12/25/2019 15:40:01 - DEBUG - BEFORE PROMPT_REPLACE: `
```
It seems that the AI have response (in fact 17 of them and it would generate more of them but I pressed CTRL+C) but something tells AI this is empty text?

Positive feedback from AI looks like this:
```
'\n> You expertly scream "Daybit please help me".\n']`
12/25/2019 15:25:37 - DEBUG - Generated result is: `'\n> You enter the portal.\nSuddenly you feel a sensation of weightlessness and you float away from the wall you were standing on. Your eyes adjust to the dark and you see a bright light. You are floating through space. Suddenly you come across some sort of machine which looks very similar to'`
12/25/2019 15:25:37 - DEBUG - Model generated empty text trying again 1
12/25/2019 15:25:37 - DEBUG - BEFORE PROMPT_REPLACE: `' 1'`
12/25/2019 15:25:37 - DEBUG - BEFORE PROMPT_REPLACE: `' 0'`
```
some lines with prompts and then
```
12/25/2019 15:25:45 - DEBUG - Stopping generation as we found stop tokens. One of [29, 50256], in 'tensor([[29]], device='cuda:0')'. token generated 57
12/25/2019 15:25:45 - DEBUG - Generated result is: `'\n\nSuddenly the voice of Daybits comes through the hole. He asks you why you came here and tells you that he has been trying to contact you since yesterday. He says he knows you were in the same class together and that he was going to give you some advice.\n'`
12/25/2019 15:25:45 - DEBUG - nAFTER RESULT_REPLACE: `'\nSuddenly the voice of Daybits comes through the hole. He asks you why you came here and tells you that he has been trying to contact you since yesterday. He says he knows you were in the same class together and that he was going to give you some advice'`
```
Full log:
```
> scream "Daybit please help me"12/25/2019 15:25:21 - DEBUG - roll d20=20

>> You expertly scream "Daybit please help me".
12/25/2019 15:25:21 - DEBUG - Using history indices range(0, 5)
12/25/2019 15:25:21 - INFO - Generated action mem_ind=None, sample=False, include_prompt=True
12/25/2019 15:25:21 - DEBUG - BEFORE PROMPT_REPLACE: `"You are Guda of Chaldea, also known as Ritsuka Fujimaru. You got your ass kicked in Atlantis by Kirshtaria Wodime who sits now in Olympus. You lost you friends in the war with Artemis, Poseidon, Echidna, Odysseus and jobbers. You have only annoying Mashu by your side and loli da Vinci. In you hearth you know, if you don't kill Kirshtaria and you don't stop his Lostbelt form expanding everything will fall.\n"`
12/25/2019 15:25:21 - DEBUG - BEFORE PROMPT_REPLACE: `"\n> You try to ask da Vinci about the hole.\n She says she is not sure what it means but that there must be something important inside. So far you haven't found anything useful in this place so you decide to go find out.\nYou head back to the Nautilus where you met Mashu\n> You miserably fail to ask Mashu how she feel.\n You just want her to tell you how she feels because you can't do it yourself.\nThen you get an idea from Da Vinci's body and start running around like a madman. You run all over the ship and eventually you manage to reach the bridge\n> You try to head up into a hidden room on the ship.\n\nYou open the door and see a room full of machinery. There is no way you could fit through it, even if you had wings. However, you notice something very strange: there is a large hole in one of the walls\n> You start to go all the way into the hole..\n\nYou make it all the way into the wall and then suddenly you feel dizzy. It seems that you fell down into a pit. You look behind you and see nothing but darkness\n> You try to yell for help.\n\nYou scream and shout, but nobody hears you. Then you realize that you're trapped. The only thing you can think of to escape this situation is to use your magic powers to create a portal to leave this place"`
12/25/2019 15:25:21 - DEBUG - BEFORE PROMPT_REPLACE: `'\n> You expertly scream "Daybit please help me".\n'`
12/25/2019 15:25:21 - DEBUG - Prompt is: `["You are Guda of Chaldea, also known as Ritsuka Fujimaru. You got your ass kicked in Atlantis by Kirshtaria Wodime who sits now in Olympus. You lost you friends in the war with Artemis, Poseidon, Echidna, Odysseus and jobbers. You have only annoying Mashu by your side and loli da Vinci. In you hearth you know, if you don't kill Kirshtaria and you don't stop his Lostbelt form expanding everything will fall.\n", "\n> You try to ask da Vinci about the hole.\n She says she is not sure what it means but that there must be something important inside. So far you haven't found anything useful in this place so you decide to go find out.\nYou head back to the Nautilus where you met Mashu\n> You miserably fail to ask Mashu how she feel.\n You just want her to tell you how she feels because you can't do it yourself.\nThen you get an idea from Da Vinci's body and start running around like a madman. You run all over the ship and eventually you manage to reach the bridge\n> You try to head up into a hidden room on the ship.\n\nYou open the door and see a room full of machinery. There is no way you could fit through it, even if you had wings. However, you notice something very strange: there is a large hole in one of the walls\n> You start to go all the way into the hole..\n\nYou make it all the way into the wall and then suddenly you feel dizzy. It seems that you fell down into a pit. You look behind you and see nothing but darkness\n> You try to yell for help.\n\nYou scream and shout, but nobody hears you. Then you realize that you're trapped. The only thing you can think of to escape this situation is to use your magic powers to create a portal to leave this place", '\n> You expertly scream "Daybit please help me".\n']`
12/25/2019 15:25:29 - DEBUG - Generated result is: `'\n> You succeed in creating a portal.\nA portal opens up before you and you enter it. You walk through it and soon you arrive at a city. A big city. You were expecting some kind of jungle or desert, but instead you see a modern city. And it looks like the'`
12/25/2019 15:25:29 - DEBUG - Model generated empty text trying again 0
12/25/2019 15:25:29 - DEBUG - BEFORE PROMPT_REPLACE: `' 0'`
12/25/2019 15:25:29 - DEBUG - BEFORE PROMPT_REPLACE: `"You are Guda of Chaldea, also known as Ritsuka Fujimaru. You got your ass kicked in Atlantis by Kirshtaria Wodime who sits now in Olympus. You lost you friends in the war with Artemis, Poseidon, Echidna, Odysseus and jobbers. You have only annoying Mashu by your side and loli da Vinci. In you hearth you know, if you don't kill Kirshtaria and you don't stop his Lostbelt form expanding everything will fall.\n"`
12/25/2019 15:25:29 - DEBUG - BEFORE PROMPT_REPLACE: `"\n> You try to ask da Vinci about the hole.\n She says she is not sure what it means but that there must be something important inside. So far you haven't found anything useful in this place so you decide to go find out.\nYou head back to the Nautilus where you met Mashu\n> You miserably fail to ask Mashu how she feel.\n You just want her to tell you how she feels because you can't do it yourself.\nThen you get an idea from Da Vinci's body and start running around like a madman. You run all over the ship and eventually you manage to reach the bridge\n> You try to head up into a hidden room on the ship.\n\nYou open the door and see a room full of machinery. There is no way you could fit through it, even if you had wings. However, you notice something very strange: there is a large hole in one of the walls\n> You start to go all the way into the hole..\n\nYou make it all the way into the wall and then suddenly you feel dizzy. It seems that you fell down into a pit. You look behind you and see nothing but darkness\n> You try to yell for help.\n\nYou scream and shout, but nobody hears you. Then you realize that you're trapped. The only thing you can think of to escape this situation is to use your magic powers to create a portal to leave this place"`
12/25/2019 15:25:29 - DEBUG - BEFORE PROMPT_REPLACE: `'\n> You expertly scream "Daybit please help me".\n'`
12/25/2019 15:25:29 - DEBUG - Prompt is: `[' 0', "You are Guda of Chaldea, also known as Ritsuka Fujimaru. You got your ass kicked in Atlantis by Kirshtaria Wodime who sits now in Olympus. You lost you friends in the war with Artemis, Poseidon, Echidna, Odysseus and jobbers. You have only annoying Mashu by your side and loli da Vinci. In you hearth you know, if you don't kill Kirshtaria and you don't stop his Lostbelt form expanding everything will fall.\n", "\n> You try to ask da Vinci about the hole.\n She says she is not sure what it means but that there must be something important inside. So far you haven't found anything useful in this place so you decide to go find out.\nYou head back to the Nautilus where you met Mashu\n> You miserably fail to ask Mashu how she feel.\n You just want her to tell you how she feels because you can't do it yourself.\nThen you get an idea from Da Vinci's body and start running around like a madman. You run all over the ship and eventually you manage to reach the bridge\n> You try to head up into a hidden room on the ship.\n\nYou open the door and see a room full of machinery. There is no way you could fit through it, even if you had wings. However, you notice something very strange: there is a large hole in one of the walls\n> You start to go all the way into the hole..\n\nYou make it all the way into the wall and then suddenly you feel dizzy. It seems that you fell down into a pit. You look behind you and see nothing but darkness\n> You try to yell for help.\n\nYou scream and shout, but nobody hears you. Then you realize that you're trapped. The only thing you can think of to escape this situation is to use your magic powers to create a portal to leave this place", '\n> You expertly scream "Daybit please help me".\n']`
12/25/2019 15:25:37 - DEBUG - Generated result is: `'\n> You enter the portal.\nSuddenly you feel a sensation of weightlessness and you float away from the wall you were standing on. Your eyes adjust to the dark and you see a bright light. You are floating through space. Suddenly you come across some sort of machine which looks very similar to'`
12/25/2019 15:25:37 - DEBUG - Model generated empty text trying again 1
12/25/2019 15:25:37 - DEBUG - BEFORE PROMPT_REPLACE: `' 1'`
12/25/2019 15:25:37 - DEBUG - BEFORE PROMPT_REPLACE: `' 0'`
12/25/2019 15:25:37 - DEBUG - BEFORE PROMPT_REPLACE: `"You are Guda of Chaldea, also known as Ritsuka Fujimaru. You got your ass kicked in Atlantis by Kirshtaria Wodime who sits now in Olympus. You lost you friends in the war with Artemis, Poseidon, Echidna, Odysseus and jobbers. You have only annoying Mashu by your side and loli da Vinci. In you hearth you know, if you don't kill Kirshtaria and you don't stop his Lostbelt form expanding everything will fall.\n"`
12/25/2019 15:25:37 - DEBUG - BEFORE PROMPT_REPLACE: `"\n> You try to ask da Vinci about the hole.\n She says she is not sure what it means but that there must be something important inside. So far you haven't found anything useful in this place so you decide to go find out.\nYou head back to the Nautilus where you met Mashu\n> You miserably fail to ask Mashu how she feel.\n You just want her to tell you how she feels because you can't do it yourself.\nThen you get an idea from Da Vinci's body and start running around like a madman. You run all over the ship and eventually you manage to reach the bridge\n> You try to head up into a hidden room on the ship.\n\nYou open the door and see a room full of machinery. There is no way you could fit through it, even if you had wings. However, you notice something very strange: there is a large hole in one of the walls\n> You start to go all the way into the hole..\n\nYou make it all the way into the wall and then suddenly you feel dizzy. It seems that you fell down into a pit. You look behind you and see nothing but darkness\n> You try to yell for help.\n\nYou scream and shout, but nobody hears you. Then you realize that you're trapped. The only thing you can think of to escape this situation is to use your magic powers to create a portal to leave this place"`
12/25/2019 15:25:37 - DEBUG - BEFORE PROMPT_REPLACE: `'\n> You expertly scream "Daybit please help me".\n'`
12/25/2019 15:25:37 - DEBUG - Prompt is: `[' 1', ' 0', "You are Guda of Chaldea, also known as Ritsuka Fujimaru. You got your ass kicked in Atlantis by Kirshtaria Wodime who sits now in Olympus. You lost you friends in the war with Artemis, Poseidon, Echidna, Odysseus and jobbers. You have only annoying Mashu by your side and loli da Vinci. In you hearth you know, if you don't kill Kirshtaria and you don't stop his Lostbelt form expanding everything will fall.\n", "\n> You try to ask da Vinci about the hole.\n She says she is not sure what it means but that there must be something important inside. So far you haven't found anything useful in this place so you decide to go find out.\nYou head back to the Nautilus where you met Mashu\n> You miserably fail to ask Mashu how she feel.\n You just want her to tell you how she feels because you can't do it yourself.\nThen you get an idea from Da Vinci's body and start running around like a madman. You run all over the ship and eventually you manage to reach the bridge\n> You try to head up into a hidden room on the ship.\n\nYou open the door and see a room full of machinery. There is no way you could fit through it, even if you had wings. However, you notice something very strange: there is a large hole in one of the walls\n> You start to go all the way into the hole..\n\nYou make it all the way into the wall and then suddenly you feel dizzy. It seems that you fell down into a pit. You look behind you and see nothing but darkness\n> You try to yell for help.\n\nYou scream and shout, but nobody hears you. Then you realize that you're trapped. The only thing you can think of to escape this situation is to use your magic powers to create a portal to leave this place", '\n> You expertly scream "Daybit please help me".\n']`
12/25/2019 15:25:45 - DEBUG - Stopping generation as we found stop tokens. One of [29, 50256], in 'tensor([[29]], device='cuda:0')'. token generated 57
12/25/2019 15:25:45 - DEBUG - Generated result is: `'\n\nSuddenly the voice of Daybits comes through the hole. He asks you why you came here and tells you that he has been trying to contact you since yesterday. He says he knows you were in the same class together and that he was going to give you some advice.\n'`
12/25/2019 15:25:45 - DEBUG - nAFTER RESULT_REPLACE: `'\nSuddenly the voice of Daybits comes through the hole. He asks you why you came here and tells you that he has been trying to contact you since yesterday. He says he knows you were in the same class together and that he was going to give you some advice'`
```

**Comment by Nalewa** [comment] 2019-12-25 15:02
```
Suggested actions:
12/25/2019 16:01:15 - DEBUG - Using history indices [0]
12/25/2019 16:01:15 - INFO - Generated action mem_ind=1, sample=1, include_prompt=0
12/25/2019 16:01:20 - DEBUG - full suggested action ' tomorrow...'. Cropped: 'tomorrow...'. Split '['tomorrow...']'
12/25/2019 16:01:20 - DEBUG - suggested action after cleaning Tomorrow..
0> Tomorrow..
12/25/2019 16:01:20 - DEBUG - Using history indices [0]
12/25/2019 16:01:20 - INFO - Generated action mem_ind=4, sample=1, include_prompt=1
12/25/2019 16:01:24 - DEBUG - full suggested action ' tomorrow! (Day of Darkness)
Tomorrow is another long one, the last time before Halloween when this world turns into night for good and then ends again for good.
'. Cropped: 'tomorrow! (Day of Darkness)'. Split '['tomorrow! (Day of Darkness)', 'Tomorrow is another long one, the last time before Halloween when this world turns into night for good and then ends again for good.']'
12/25/2019 16:01:24 - DEBUG - suggested action after cleaning Tomorrow! (Day of Darkness)
1> Tomorrow! (Day of Darkness)
12/25/2019 16:01:24 - DEBUG - Using history indices range(0, 1)
12/25/2019 16:01:24 - INFO - Generated action mem_ind=5, sample=0, include_prompt=0
12/25/2019 16:01:28 - DEBUG - full suggested action ' tomorrow... (Day of Judgment)
You don't think too much about what your mom told you yesterday, but on this particular day you feel a lot different from before so'. Cropped: 'tomorrow... (Day of Judgment)'. Split '['tomorrow... (Day of Judgment)', "You don't think too much about what your mom told you yesterday, but on this particular day you feel a lot different from before so"]'
12/25/2019 16:01:28 - DEBUG - suggested action after cleaning Tomorrow... (Day of Judgment)
2> Tomorrow... (Day of Judgment)
12/25/2019 16:01:28 - DEBUG - Using history indices [0]
12/25/2019 16:01:28 - INFO - Generated action mem_ind=2, sample=1, include_prompt=1
12/25/2019 16:01:34 - DEBUG - full suggested action ' day 2
Today is Sunday which means that school is over, at least for now. Kirsch knows its time to fight anyway so you should all be able to relax until'. Cropped: 'day 2'. Split '['day 2', 'Today is Sunday which means that school is over, at least for now. Kirsch knows its time to fight anyway so you should all be able to relax until']'
12/25/2019 16:01:34 - DEBUG - suggested action after cleaning Day 2
3> Day 2
```
sometime the suggestions are still random kek

**Comment by Nalewa** [comment] 2019-12-25 15:11
```
12/25/2019 16:09:37 - DEBUG - Generated result is: `'html]\n<|startoftext|>"Kirishima-san! Are you still alive? We need you!"\n\n"Yeah, I\'m alive." He answers.\n\n"We need to hurry, we\'re going to meet someone important."\n\n"Who is it'`
12/25/2019 16:09:37 - DEBUG - nAFTER RESULT_REPLACE: `'html]'`

html]
```
funny example of cutted content

**Comment by Nalewa** [comment] 2019-12-25 15:35
```
12/25/2019 16:34:18 - DEBUG - Generated result is: `'\n\n"Kirshtaria? That guy who lives in the Lostbelt? He\'s the one that\'s going to kill you. He\'s been trying to expand his territory ever since he got his hands on the Lostbelt. He\'s already killed a few other people in the process of doing so. He\'s a very dangerous man. He\'s also a madman, but he\'s not stupid. If you want to survive, you need to stay away from him. I\'d suggest you don\'t go too far from here though, he\'s got a lot of people stationed all over'`
12/25/2019 16:34:18 - DEBUG - nAFTER RESULT_REPLACE: `'\n'`
```
empty result not taken as empty, it just post enter

**Comment by Gabriram** [comment] 2019-12-25 16:32
So the new_suggestions_with_context branch is still the most stable one right?

@AtaIanta i enjoyed your shitty fanfiction, you are worth kap 286,065,238

**Comment by AtaIanta** [comment] 2019-12-25 16:40
`new_suggestions_with_context` seems to be stable and gives decent input as long as you don't do something complicate 

>286,065,238
added, Merlin on all

**Comment by Meanmelter** [comment] 2019-12-25 21:58
Hm I had the issues Gabriram had when I didn't have that file, but I think you might be right. I have not installed the new suggestions that AccidentlyOnPurpose configured, I started a new context this morning (Continuing off of an old story) and here is something I was getting when the AI generated a response.
![image](https://user-images.githubusercontent.com/17638040/71450835-b44f4580-2737-11ea-8a75-3d205821ed34.png)
I will try the new branch and see if the same is still happening.

**Comment by Meanmelter** [comment] 2019-12-25 22:05
Can confirm no longer getting that issue.
Also, good job AccidentlyOnPurpose these suggestions are pretty damn good. (Different prompt, first part of story tho.)
![image](https://user-images.githubusercontent.com/17638040/71450891-acdc6c00-2738-11ea-8a65-ffecbbf7e293.png)

**Comment by Gabriram** [comment] 2019-12-25 23:06
Sometimes i still get 
```` 12/26/2019 00:03:07 - WARNING - Model generated empty text 20 times. Try another action
Woops that action caused the model to start looping. Try a different action to prevent that.````

**Comment by AccidentallyOnPurpose** [comment] 2019-12-26 00:52
Thanks for all those logs. There's a lot going on, but I'll try to unpack it

1) The model kept generating an action (starts with ">") instead of a story. So the code throws away everything after the ">" (this is what all forks do I think). But now the model generated nothing? So lets try again 20 times.

I don't see anything in your prompt that would be causing it.

Why 17, 16, etc? Well it's something I tried. If we are going to try again lets make the action differen't right? So I add a number to the start. Doesn't seem to have helped, so I'll remove that or put it on the end. So yeah ignore that.

Suggestion on what to do here? Maybe we should keep the action? Maybe we should remove the action but keep the story after the action. I think these changes will need playtesting since they could fix this but break other things.

2) Action are def random kek
Yup!

3) `html]`

Not sure what to do here. E.g. how do we know that html] is bad context? I guess the models just gone bad (off track here) and I'm not sure we could detect that in a general and reliable sense without some quite complicted algorithms.

**Comment by AccidentallyOnPurpose** [comment] 2019-12-26 01:02
For 1, I pushed an change that says "if cleaning made blank text, try again, this time allowing ">" (actions)". Lets see if that improves it.

**Comment by AccidentallyOnPurpose** [comment] 2019-12-26 03:39
@meanmelter suggestion are good, that on the new branch?

I made a change to the suggestion, now they sometimes suggest pure dialouge.

**Comment by Meanmelter** [comment] 2019-12-26 05:37
@AccidentallyOnPurpose Sorry! Yes they are good for me! Sorry I meant to update you more earlier but I wasn't sure where to type to you.
I am having some issues where the AI doesn't respond to my Say commands, but it might just be how it's formatting, that's also a different issue anyway.

**Comment by Meanmelter** [comment] 2019-12-26 06:01
Some examples
![image](https://user-images.githubusercontent.com/17638040/71460113-7f171780-2778-11ea-942f-89cc196a51d9.png)
![image](https://user-images.githubusercontent.com/17638040/71460578-6b6cb080-277a-11ea-84fd-c06898c441af.png)
![image](https://user-images.githubusercontent.com/17638040/71460781-475d9f00-277b-11ea-8200-2c45f2d262f5.png)
It seems to often end the speech responses without adding quotes or content for it. Again might just be how the AI picks up the formatting from my previous posts?

**Comment by AccidentallyOnPurpose** [comment] 2019-12-26 06:10
I see, I that's just the AI being derpy. 

People were amazed it learned about speech marks and stuff just from reading the internet. It even learnt to code... but the code had lots of typos.

There are even specific weights inside the model that seem to keep track of speech marks.. but it's all probabilistic so sometimes it's derpy and forgets who's who, or where you are in terms of speech marks.

So just a limiation of the current generation of ML models.

**Comment by AtaIanta** [comment] 2019-12-26 06:10
still gives empty responses, but you can press enter without writing anything to force AI to say something
![image](https://user-images.githubusercontent.com/42716753/71460936-2ebaac80-27ae-11ea-90d1-5808743dcc7c.png)

also in log the enters are not changing in prompt to \n so i was forced to disable debug option's to read something
![image](https://user-images.githubusercontent.com/42716753/71461009-81946400-27ae-11ea-99d0-edefc8929a66.png)

but the suggestions are now perfect

**Comment by AccidentallyOnPurpose** [comment] 2019-12-26 06:18
Great that the suggestions are working

For the logging it's just for us, but you can change the %s to a %r to make it print \n instead of an actual newline. E.g.
```
logger.info('%r', """

line

line

""")
```
# 12/26/2019 14:17:44 - INFO - '\n\nline\n\nline\n\n'

**Comment by AccidentallyOnPurpose** [comment] 2019-12-26 06:24
Ok I'll merge this new branch since it seems stable and to behave well

**Comment by AtaIanta** [comment] 2019-12-26 06:27
Sometimes the AI doesn't do what user said but I think is due to the lack of training

![image](https://user-images.githubusercontent.com/42716753/71461678-05e7e680-27b1-11ea-9378-ba1340799bd4.png)

**Comment by AccidentallyOnPurpose** [comment] 2019-12-26 06:33
True and a bit of AI derpyness

**Comment by AccidentallyOnPurpose** [comment] 2019-12-26 06:37
On the new branch (now merged) I made the prompt "You >" instead of ">". This is an attempt to show anons that they need to write in second person. Let me know if you guys think it works, doesn't, better idea.

**Comment by AtaIanta** [comment] 2019-12-26 06:40
It's good addition, I must say that sometimes it remided me to write in second person.

**Closed** 2019-12-26 08:06 UTC
